dist-hook rule updated : should fail when 'sed' fails

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -120,8 +120,11 @@ doc:
 	done)
 
 dist-hook:
-	(for f in `find $(distdir) | grep -E '\.(c|h|java)$$'`; do \
-	echo $$f; \
-	sed -E -e '/\$$Id.*\$$/ r $(top_builddir)/LICENCE' $$f > $$f.tmp; \
-	mv $$f.tmp $$f; \
-	done)
+	set -e; \
+	for f in `find $(distdir) | grep -E '\.(c|h|java)$$'`; do \
+	  echo "update licence $$f"; \
+	  sed -E -e '/\$$Id.*\$$/ r $(top_builddir)/LICENCE' $$f > $$f.tmp; \
+	  mv $$f.tmp $$f; \
+	done
+
+# || (echo "Error when 'sed'ing $$f"; exit 1);
